### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by ghost** [loosewheel/lwcomputers#3]
1)Add keyboard entering support
2)Make the computer a separate block
3)Add components for the computer, from which you can build it

**Comment by loosewheel** [comment]
There is a keyboard digilines device that can be used. You would likely need to override os.get_event and os.peek_event to implement it. If the keyboard is a separate block you can't see the terminal while using the keyboard. You'll need to flick back and forth between them. There is a plan to send key events to formspecs in minetest. When this happens the keyboard my be able to be removed, and use your real keyboard instead.

Making the crafting more complicated and more expensive is possible. I intentional made them reasonably cheap so they can be used in survival mode. Many complex mods make their items very expensive. By the time you've got the resources to craft them you don't need them anymore. I use the robots and computers in survival mode. After you've overcome the challenge of digging down a couple of hundred blocks to get the iron and copper, you can then use robots and computers to do things to make the game play more interesting.

**Comment by ghost** [comment]
I mean what in computer i cant enter text from my real keyboard. only from GUI. And if you add separated screens with terminal (like in OpenComputers). Or you can add digiterms support for terminal output

**Comment by ghost** [comment]
> Making the crafting more complicated and more expensive is possible. I intentional made them reasonably cheap so they can be used in survival mode. Many complex mods make their items very expensive. By the time you've got the resources to craft them you don't need them anymore. I use the robots and computers in survival mode. After you've overcome the challenge of digging down a couple of hundred blocks to get the iron and copper, you can then use robots and computers to do things to make the game play more interesting.

I not mean crafting, i mean upgrades, like types of cpu`s, gpu`s, disks and screens with different performances. And its be cool if you add sreens what have pixels, and what can work like a normal screen with pictures. Like screens in Minecraft OpenComputers mode.
